config/routes.rb
Rails.application.routes.draw do

  root             'users#new'
  get 'users/new'
  get 'signup'  => 'users#new'
  get 'users/new'

  # Facebook Login
  get 'sessions/create'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'


  #dashboard
  get 'dashboards/new', to: 'dashboards#new'
  get '/dashboard', to: 'dashboards#user', as: 'dashboard'
  post '/dashboard', to: 'dashboards#create'

  #trips
  get '/trips/', to: 'trips#show'

  #inbox
  get '/inbox/', to: 'inboxs#show'

  #profile
  get 'profiles/new', to: 'profiles#new'
  get '/profile', to: 'profiles#user', as: 'profile'
  post '/profile', to: 'profiles#create'

  resource :friends
end

app/models/trip.rb
class Trip < ActiveRecord::Base
    belongs_to :user

    validates :user_id, presence: true
    validates :city, presence: true
    validates :country, presence: true
end

app/models/trip/handlers/activity_handler.rb
module Trips
  module Handlers
    class ActivityHandler

      def initialize(trip)
        @trip = trip
      end

      def update(user_activity)
        trip.update_attribute(:activity, user_activity)
      end

    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :trips, dependent: :destroy

  def self.omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.nickname = auth.info.nickname
      
      fname = auth.info.first_name
      fname = "" if fname.blank?
      user.first_name = fname

      lname = auth.info.last_name
      lname = "" if lname.blank?
      user.last_name = lname

      location = auth.info.location
      location = "" if location.blank?
      user.location = location      

      description = auth.info.description
      description = "" if description.blank?
      user.description = description  

      user.image = auth.info.image
      user.token = auth.credentials.token
      user.expires_at = auth.check_for_expires_at_returned()
      user.save!
    end
  end
  
  private
  
  def check_for_expires_at_returned()
    if (auth.credentials.expires_at)
      Time.at(auth.credentials.expires_at)
    else
      nil
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def setup_user
    params.permit!
    @trip = Trip.new(params[:trip])
    current_user.trips.push(@trip)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  include SessionsHelper

  expose(:dashboard) { DashboardView.new(current_user) }
  expose(:buttons)   { Buttons.new }
  expose(:labels)    { Labels.new }
  expose(:friends) { Friends.new(current_user) }
  expose(:user_view) { UserView.new(current_user) }

  def create
    params.permit!
    @trip = Trip.new(params[:trip])
    #prob want to update attributes instead
    current_user.trips.push(@trip)

    redirect_to '/dashboard'
  end

  def user
    @user = current_user
    @trips = current_user.trips.paginate(page: params[:page])
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  expose(:friends) { Friends.new(current_user) }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include SessionsHelper

  expose(:profile)
  expose(:user_view) { UserView.new(current_user) }
  expose(:buttons)   { Buttons.new }
  expose(:labels)    { Labels.new }
  expose(:activity)  { Activity.new }

  def create
    params.permit!
    @profile = Profile.new(params[:trip])
    current_user.update_attribute(:profile, @profile)

    redirect_to '/profile'
  end

  def user
    @user = current_user
    @trips = current_user.trips.paginate(page: params[:page])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def create
    user = User.omniauth(env['omniauth.auth'])
    session[:user_id] = user.id

    redirect_to '/dashboard'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  include SessionsHelper
  expose(:trip)

  def show
    params.permit!
    @user = current_user
    @trips = current_user.trips.paginate(page: params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  expose(:user)

  def user_params
    params.require(:user).permit(:name, :email, :nickname, :first_name, :last_name, :location, :description, :password, :provider, :image, :token, :expires_at, :uid)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "SheNomads Tracker"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/_main.html.haml
.col-sm-4
  .thumbnail
    %p
      %strong
        = labels.inbox
    %p 10 messages
    %button.btn
      Open
.col-sm-4
  .thumbnail
    %p
      %strong
        = labels.upcoming_trips
    %p= dashboard.trip_count
    %button.btn
      = buttons.update
.col-sm-4
  .thumbnail
    %p
      %strong Past Trips
    %p 4
    %button.btn
      = labels.take_a_look
.col-sm-4
  .thumbnail
    %p
      %strong
        = labels.ask_me_about
    %p 3
    %button.btn
      = buttons.update
.col-sm-4
  .thumbnail
    %p
      %strong
        = labels.meet_me_for
    %p 3
    %button.btn
      = buttons.update
.col-sm-4
  .thumbnail
    %p
      %strong
        = labels.friends
    %p
      = "3"
    %button.btn
      = link_to buttons.update,  friends_path

app/views/dashboards/_sidebar.html.haml
%ul
  = image_tag user_view.image + user_view.image_size
  = user_view.name
  %h5 Edit Profile

app/views/dashboards/user.html.haml
.container-fluid
  .row-fluid
    .span3
      = render "dashboards/sidebar"
    .span9
      <!--Body content-->
      .row.text-center
        = render "dashboards/main"

app/views/friends/show.html.haml
.container-fluid
  .row-fluid
    .span12
      .row.text-center
        .col-sm-4
          .thumbnail
            %p
              %strong
                = "Maya"
            %p Tel Aviv
        .col-sm-4
          .thumbnail
            %p
              %strong
                = "Lorena"
            %p= "Bilboa"
        .col-sm-4
          .thumbnail
            %p
              %strong
                = "Dori"
            %p Bilboa
        .col-sm-4
          .thumbnail
            %p
              %strong
                = "Charlie"
            %p= "Barcelona"
        .col-sm-4
          .thumbnail
            %p
              %strong
                = "Diana"
            %p=  "Lisboa"
        .col-sm-4
          .thumbnail
            %p
              %strong
                = "Magdelena"
            %p=   "Lisbon"

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "SheNomads", '#', id: "logo" %>
    <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search SheNomads">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
    <nav>
      <ul class="nav navbar-nav navbar-right">
       <% if logged_in? %>
        <li><%= link_to "Dashboard",   '/dashboard' %></li>
        <li><%= link_to "Inbox",   '/inbox' %></li>
        <li><%= link_to "Your Trips",   '/trips' %></li>
        <li><%= link_to "Profile",   '/profile' %></li>
        <li><%= link_to "Log Out", '/logout' %></li>
       <% else %>
        <li><%= link_to "Log in Via Facebook", '/auth/facebook' %></li>
        <li><%= link_to "Log in Via Twitter", '/auth/twitter' %></li>
       <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" rel="stylesheet">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <%= yield %>
  </body>
</html>

app/views/profiles/_activity.html.haml
%p
  %strong
    = labels.meet_me_in + trip.city + labels.for
%p
  %strong
    = trip.activity
%p
  = activity.format(trip.activity_date)
%button.btn
  = "Lets Go!"
%button.btn
  = "Lets do something else"

app/views/profiles/_user_sidebar.html.haml
%ul.profile
  %li= image_tag user_view.image + user_view.image_size
  %li= "name: " + user_view.name
  %li= "nickname: " + user_view.nickname
  %li= "first_name: " + user_view.first_name
  %li= "last_name: " + user_view.last_name
  %li= "location: " + user_view.location
  %li= "description: " + user_view.description

app/views/profiles/user.html.haml
.container-fluid
  .row-fluid
    .span3
      = render "profiles/user_sidebar"

    .span9
      .row.text-center
        - user_view.trips.each do |trip|
          .col-sm-4
            .thumbnail
              = render "profiles/activity", trip: trip

app/views/trips/show.html.erb
<% if current_user.trips.count == 0 %>
  <h1>You have no trips planned, <%= current_user.name %> . </h1>
  <h1>Where are you going ? </h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(:trip ) do |f| %>
        <%= f.label :city %>
        <%= f.text_field :city, class: 'form-control' %>

        <%= f.label :country %>
        <%= f.text_field :country, class: 'form-control' %>

        <%= f.submit "Add A Trip", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% else %>
  <div>
  <% @trips.each do |trip| %>
    <%= trip.city =%>,
    <%= trip.country =%>
    <%= trip.in %>
    <%= trip.out %>
  <% end %>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Where are you going? </h1>
<h1>Find fellow travelers on SheNomads</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:search ) do |f| %>
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.submit "Find Nomads", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>